### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by MohaKh1** [KevinZheng14815/Hackathon#10]
# Overview

# Todo List
- [x] create react app
- [x] install dependencies
- [ ] push to github

# Core
- [x] Routes

# Homepage
- [x] basic structure
- [x] stuff
# Prediction Page
- [x]  Prediction input form
- [x] Prediction Result pane
- [x] Graph view <- (prediction user input)
- [ ]

**Comment by fygure** [comment]
opening new issue after project pivot
