### ISSUE TITLE
Api + Data analysis

### ISSUE THREAD

**Issue by MohaKh1** [KevinZheng14815/Hackathon#11]
# Todo
- [x] Kernel Ridge Regression
- [ ] Middle East Oil Production (Mohamed)
- [ ] Oil Reserves (Oil Reserves)
- [ ] Stock Prices ()

**Comment by KevinZheng14815** [comment]
closed
